### PR TITLE
Implementation of an alternate way to retrieve the tree in List form

### PR DESCRIPTION
**Pull request by andrewliles**
See my motivation here: https://github.com/davidsusu/tree-printer/issues/9

I have PR for you here where I changed the `ListingTreePrinter` to offer a new public method for retrieving an ordered list of items which give granular access to the original `TreeNode`, the `ConsoleContent` and the constructed `prefix`.  I created a `ListingTreeNode` to carry this data.

I was tempted to refactor the Tree to write into `List<ListingTreeNode>` and then use this to produce the original text output, but I noticed that your original implementation was aiming to be memory efficient by using `Appendable`, so you'll see a kept this approach; my List construction approach breaks this goal.

To ensure I did not break existing functionality I wrote several unit tests beforehand, and they pass after my change.

(Sorry for the many whitespace changes in `ListingTreePrinter.java` - my IDE took out a load of spaces, which was only clear to me when reviewing here.)

### CODE REVIEW

**Comment by davidsusu** [comment]
Thank you for the pull request, and special thanks for the unit tests.

I would just like to make some little changes in the API.

First, the name `ListingTreeNode` is a bit confusing because it's more an output line entry than a node.
Also, from `3.x` we should provide `ConsoleText` instead of `String`. So, please refactor this:

```java
public class ListingTreeNode {

    private final TreeNode node;

    private final String prefix;

    private final String line;

    // ...
    
}
```

to something like this:

```java

public class ListingLineEntry {

    private final TreeNode node;

    private final ConsoleText liningPrefix;

    private final ConsoleText contentLine;

    // ...
    
}
```

To be consistent, please rename `getListingTreeNodes()` to `collectLineEntries()`.

Otherwise everything looks great to me, so I will merge it after you push the above changes.
This feature will be part of version `3.1.0`.

**Review by davidsusu — CHANGES_REQUESTED** [review]
@andrewliles 

So my requested changes are:

- Rename `ListingTreeNode` to `ListingLineEntry`
- Change `String` field types to `ConsoleText` in it
- Rename `getListingTreeNodes(...)` to `collectLineEntries(...)` in `ListingTreePrinter`

**Comment by andrewliles** [comment]
You should see a second commit where :

* Renamed `ListingTreeNode` to `ListingLineEntry`
* Renamed `getListingTreeNodes(...)` to `collectLineEntries(...)`

However, I have not made the `ConsoleText` change yet, because I don't understand what you want.

I was capturing the output of the `ListingTreePrinter` **after** the content is rendered from the the `ConsoleText` to a String:

In `ListingTreePrinter.printContentLine()` you had this:

```
String itemPrefix = buildItemPrefix(disposition, hasChildren, inset, connectOffset, i);
String fullPrefix = prefix + itemPrefix;
String formattedFullPrefix = Util.getStringContent(ConsoleText.of(fullPrefix).format(liningFormat), ansiMode);
Util.writeln(out, formattedFullPrefix + line);
```

and I just changed the last line to:
```
sink.writeln(node, formattedFullPrefix, line);
```

If you are suggesting that the "sink" needs to receive the ConsoleText so that a user of `ListingLineEntry` can then apply the ansi write, it would also mean that this ansi handling needs to be pushed down into the `AppendableListingOutputSink` as well, so that the ultimate behaviour remains the same.   This means we need to pass down `liningFormat` and `ansiMode`

**Comment by davidsusu** [comment]
Thank you for the changes.

You are right, now I see that some more refactoring is required to achieve support for `ConsoleText` in `ListingLineEntry`.

IMO `AppendableListingOutputSink` should have a constructor parameter for `ansiMode` and `ListingOutputSink.writeln(...)` should accept `ConsoleText` parameters instead of `String`.

The same is true for `ListingTreePrinter.printContentLine(...)`. In `ListingTreePrinter.printSub(...)` you can pass `ConsoleText`, for example in this way:

```diff
- String content = Util.getStringContent(node.content(), ansiMode);
  // ...
- String[] lines = TextUtil.linesOf(content);
+ ConsoleText[] lines = TextUtil.linesOf(node.content());
```

Also, this is safer. Of course, it's my fault that I didn't solve it that way.

It would be great if you could include these changes as well. That way, after the merge, I would no longer need to change the API and there would be no hassles.

I look forward to your final version and thank you for your work.

**Review by davidsusu — CHANGES_REQUESTED** [review]
@andrewliles 

Needed remaining changes:

- Add `ansiMode` as a constructor parameter to `AppendableListingOutputSink`
- Accept `ConsoleText` parameters in `ListingOutputSink.writeln(...)`
- Accept `line` parameter as `ConsoleText` in `ListingTreePrinter.printContentLine(...)`
- Refactor `ListingTreePrinter.printSub(...)` as required

**Comment by davidsusu** [comment]
Just a clarifying note.

In `ListingTreePrinter.printContentLine(...)`, there is no need to pass additional parameters to the sink. `ansiMode` should already be set (in the case of `AppendableListingOutputSink`). `liningFormat` is part of the `ConsoleText`:

```java
ConsoleText formattedFullPrefix = ConsoleText.of(fullPrefix).format(liningFormat);

**Comment by andrewliles** [comment]
OK, that's done, but to be honest, I have not validated that the **ansi** output is handled correctly as I don't know much about how it works and there are no Unit Tests to ensure the ansi implementation remains good (my plain text rendered tree passes just fine).  Please study carefully.

**Comment by davidsusu** [comment]
Good job, thank you. However, you don't have to give the `ansiMode` to `ListingLineEntry` (see my comment above). Instead of

```java
String stringLine = entry.getStringContentLine();
```

you can just:

```java
String stringLine = entry.getContentLine().plain();
```

Demeter is on vacation. :wink:

**Review by davidsusu — CHANGES_REQUESTED** [review]
Requested changes:

- Remove `getStringLiningPrefix()` and `getStringContentLine()` from `ListingLineEntry`
- Remove the `ansiMode` dependency from `ListingLineEntry`

**Comment by davidsusu** [comment]
Finally, I merged this pull request with some minor changes.

**Comment by davidsusu** [comment]
@andrewliles

In the PR commits, you used a different email address than your primary email. If possible, please assign this address to your user so that you appear in the list of contributors. Thank you, and have a nice day!

**Comment by andrewliles** [comment]
Dávid, 
Hmm, I didn't realise my git client was leaking a different email address. OK, so I have added this to Github.

**Pull request merged**
